/*
 * LineAwesome for CK Editor
 *
 * Authors	: Michael Janea (www.michaeljanea.com):
 *              - creator of the original FontAwesome plugin (v1.0 - v1.2)
 *            Juergen Krausz (www.grafikrausz.at):
 *              - updated for LineAwesome https://icons8.de/line-awesome
 *              - some other small modifications
 *
 * Version	: 1.1
 *
 */

var lineawesome = '';

var icons = [
  ['las la-american-sign-language-interpreting', 'American sign language interpreting'],
  ['las la-assistive-listening-systems', 'Assistive listening systems'],
  ['las la-audio-description', 'Audio description'],
  ['las la-blind', 'Blind'],
  ['las la-braille', 'Braille'],
  ['las la-closed-captioning', 'Closed captioning'],
  ['las la-deaf', 'Deaf'],
  ['las la-low-vision', 'Low vision'],
  ['las la-phone-volume', 'Phone volume'],
  ['las la-question-circle', 'Question circle'],
  ['las la-sign-language', 'Sign language'],
  ['las la-tty', 'Tty'],
  ['las la-universal-access', 'Universal access'],
  ['las la-wheelchair', 'Wheelchair'],
  ['las la-bell', 'Bell'],
  ['las la-bell-slash', 'Bell slash'],
  ['las la-exclamation', 'Exclamation'],
  ['las la-exclamation-circle', 'Exclamation circle'],
  ['las la-exclamation-triangle', 'Exclamation triangle'],
  ['las la-radiation', 'Radiation'],
  ['las la-radiation-alt', 'Radiation alt'],
  ['las la-skull-crossbones', 'Skull crossbones'],
  ['las la-cat', 'Cat'],
  ['las la-crow', 'Crow'],
  ['las la-dog', 'Dog'],
  ['las la-dove', 'Dove'],
  ['las la-dragon', 'Dragon'],
  ['las la-feather', 'Feather'],
  ['las la-feather-alt', 'Feather alt'],
  ['las la-fish', 'Fish'],
  ['las la-frog', 'Frog'],
  ['las la-hippo', 'Hippo'],
  ['las la-horse', 'Horse'],
  ['las la-horse-head', 'Horse head'],
  ['las la-kiwi-bird', 'Kiwi bird'],
  ['las la-otter', 'Otter'],
  ['las la-paw', 'Paw'],
  ['las la-spider', 'Spider'],
  ['las la-angle-double-down', 'Angle double down'],
  ['las la-angle-double-left', 'Angle double left'],
  ['las la-angle-double-right', 'Angle double right'],
  ['las la-angle-double-up', 'Angle double up'],
  ['las la-angle-down', 'Angle down'],
  ['las la-angle-left', 'Angle left'],
  ['las la-angle-right', 'Angle right'],
  ['las la-angle-up', 'Angle up'],
  ['las la-arrow-alt-circle-down', 'Arrow alt circle down'],
  ['las la-arrow-alt-circle-left', 'Arrow alt circle left'],
  ['las la-arrow-alt-circle-right', 'Arrow alt circle right'],
  ['las la-arrow-alt-circle-up', 'Arrow alt circle up'],
  ['las la-arrow-circle-down', 'Arrow circle down'],
  ['las la-arrow-circle-left', 'Arrow circle left'],
  ['las la-arrow-circle-right', 'Arrow circle right'],
  ['las la-arrow-circle-up', 'Arrow circle up'],
  ['las la-arrow-down', 'Arrow down'],
  ['las la-arrow-left', 'Arrow left'],
  ['las la-arrow-right', 'Arrow right'],
  ['las la-arrow-up', 'Arrow up'],
  ['las la-arrows-alt', 'Arrows alt'],
  ['las la-arrows-alt-h', 'Arrows alt h'],
  ['las la-arrows-alt-v', 'Arrows alt v'],
  ['las la-caret-down', 'Caret down'],
  ['las la-caret-left', 'Caret left'],
  ['las la-caret-right', 'Caret right'],
  ['las la-caret-square-down', 'Caret square down'],
  ['las la-caret-square-left', 'Caret square left'],
  ['las la-caret-square-right', 'Caret square right'],
  ['las la-caret-square-up', 'Caret square up'],
  ['las la-caret-up', 'Caret up'],
  ['las la-cart-arrow-down', 'Cart arrow down'],
  ['las la-chart-line', 'Chart line'],
  ['las la-chevron-circle-down', 'Chevron circle down'],
  ['las la-chevron-circle-left', 'Chevron circle left'],
  ['las la-chevron-circle-right', 'Chevron circle right'],
  ['las la-chevron-circle-up', 'Chevron circle up'],
  ['las la-chevron-down', 'Chevron down'],
  ['las la-chevron-left', 'Chevron left'],
  ['las la-chevron-right', 'Chevron right'],
  ['las la-chevron-up', 'Chevron up'],
  ['las la-cloud-download-alt', 'Cloud download alt'],
  ['las la-cloud-upload-alt', 'Cloud upload alt'],
  ['las la-compress-arrows-alt', 'Compress arrows alt'],
  ['las la-download', 'Download'],
  ['las la-exchange-alt', 'Exchange alt'],
  ['las la-expand-arrows-alt', 'Expand arrows alt'],
  ['las la-external-link-alt', 'External link alt'],
  ['las la-external-link-square-alt', 'External link square alt'],
  ['las la-hand-point-down', 'Hand point down'],
  ['las la-hand-point-left', 'Hand point left'],
  ['las la-hand-point-right', 'Hand point right'],
  ['las la-hand-point-up', 'Hand point up'],
  ['las la-hand-pointer', 'Hand pointer'],
  ['las la-history', 'History'],
  ['las la-level-down-alt', 'Level down alt'],
  ['las la-level-up-alt', 'Level up alt'],
  ['las la-location-arrow', 'Location arrow'],
  ['las la-long-arrow-alt-down', 'Long arrow alt down'],
  ['las la-long-arrow-alt-left', 'Long arrow alt left'],
  ['las la-long-arrow-alt-right', 'Long arrow alt right'],
  ['las la-long-arrow-alt-up', 'Long arrow alt up'],
  ['las la-mouse-pointer', 'Mouse pointer'],
  ['las la-play', 'Play'],
  ['las la-random', 'Random'],
  ['las la-recycle', 'Recycle'],
  ['las la-redo', 'Redo'],
  ['las la-redo-alt', 'Redo alt'],
  ['las la-reply', 'Reply'],
  ['las la-reply-all', 'Reply all'],
  ['las la-retweet', 'Retweet'],
  ['las la-share', 'Share'],
  ['las la-share-square', 'Share square'],
  ['las la-sign-in-alt', 'Sign in alt'],
  ['las la-sign-out-alt', 'Sign out alt'],
  ['las la-sort', 'Sort'],
  ['las la-sort-alpha-down', 'Sort alpha down'],
  ['las la-sort-alpha-down-alt', 'Sort alpha down alt'],
  ['las la-sort-alpha-up', 'Sort alpha up'],
  ['las la-sort-alpha-up-alt', 'Sort alpha up alt'],
  ['las la-sort-amount-down', 'Sort amount down'],
  ['las la-sort-amount-down-alt', 'Sort amount down alt'],
  ['las la-sort-amount-up', 'Sort amount up'],
  ['las la-sort-amount-up-alt', 'Sort amount up alt'],
  ['las la-sort-down', 'Sort down'],
  ['las la-sort-numeric-down', 'Sort numeric down'],
  ['las la-sort-numeric-down-alt', 'Sort numeric down alt'],
  ['las la-sort-numeric-up', 'Sort numeric up'],
  ['las la-sort-numeric-up-alt', 'Sort numeric up alt'],
  ['las la-sort-up', 'Sort up'],
  ['las la-sync', 'Sync'],
  ['las la-sync-alt', 'Sync alt'],
  ['las la-text-height', 'Text height'],
  ['las la-text-width', 'Text width'],
  ['las la-undo', 'Undo'],
  ['las la-undo-alt', 'Undo alt'],
  ['las la-upload', 'Upload'],
  ['las la-backward', 'Backward'],
  ['las la-broadcast-tower', 'Broadcast tower'],
  ['las la-circle', 'Circle'],
  ['las la-compress', 'Compress'],
  ['las la-eject', 'Eject'],
  ['las la-expand', 'Expand'],
  ['las la-fast-backward', 'Fast backward'],
  ['las la-fast-forward', 'Fast forward'],
  ['las la-file-audio', 'File audio'],
  ['las la-file-video', 'File video'],
  ['las la-film', 'Film'],
  ['las la-forward', 'Forward'],
  ['las la-headphones', 'Headphones'],
  ['las la-microphone', 'Microphone'],
  ['las la-microphone-alt', 'Microphone alt'],
  ['las la-microphone-alt-slash', 'Microphone alt slash'],
  ['las la-microphone-slash', 'Microphone slash'],
  ['las la-music', 'Music'],
  ['las la-pause', 'Pause'],
  ['las la-pause-circle', 'Pause circle'],
  ['las la-photo-video', 'Photo video'],
  ['las la-play-circle', 'Play circle'],
  ['las la-podcast', 'Podcast'],
  ['las la-rss', 'Rss'],
  ['las la-rss-square', 'Rss square'],
  ['las la-step-backward', 'Step backward'],
  ['las la-step-forward', 'Step forward'],
  ['las la-stop', 'Stop'],
  ['las la-stop-circle', 'Stop circle'],
  ['las la-tv', 'Tv'],
  ['las la-video', 'Video'],
  ['las la-volume-down', 'Volume down'],
  ['las la-volume-mute', 'Volume mute'],
  ['las la-volume-off', 'Volume off'],
  ['las la-volume-up', 'Volume up'],
  ['las la-air-freshener', 'Air freshener'],
  ['las la-ambulance', 'Ambulance'],
  ['las la-bus', 'Bus'],
  ['las la-bus-alt', 'Bus alt'],
  ['las la-car', 'Car'],
  ['las la-car-alt', 'Car alt'],
  ['las la-car-battery', 'Car battery'],
  ['las la-car-crash', 'Car crash'],
  ['las la-car-side', 'Car side'],
  ['las la-charging-station', 'Charging station'],
  ['las la-gas-pump', 'Gas pump'],
  ['las la-motorcycle', 'Motorcycle'],
  ['las la-oil-can', 'Oil can'],
  ['las la-shuttle-van', 'Shuttle van'],
  ['las la-tachometer-alt', 'Tachometer alt'],
  ['las la-taxi', 'Taxi'],
  ['las la-truck', 'Truck'],
  ['las la-truck-monster', 'Truck monster'],
  ['las la-truck-pickup', 'Truck pickup'],
  ['las la-apple-alt', 'Apple alt'],
  ['las la-campground', 'Campground'],
  ['las la-cloud-sun', 'Cloud sun'],
  ['las la-drumstick-bite', 'Drumstick bite'],
  ['las la-football-ball', 'Football ball'],
  ['las la-hiking', 'Hiking'],
  ['las la-mountain', 'Mountain'],
  ['las la-tractor', 'Tractor'],
  ['las la-tree', 'Tree'],
  ['las la-wind', 'Wind'],
  ['las la-wine-bottle', 'Wine bottle'],
  ['las la-beer', 'Beer'],
  ['las la-blender', 'Blender'],
  ['las la-cocktail', 'Cocktail'],
  ['las la-coffee', 'Coffee'],
  ['las la-flask', 'Flask'],
  ['las la-glass-cheers', 'Glass cheers'],
  ['las la-glass-martini', 'Glass martini'],
  ['las la-glass-martini-alt', 'Glass martini alt'],
  ['las la-glass-whiskey', 'Glass whiskey'],
  ['las la-mug-hot', 'Mug hot'],
  ['las la-wine-glass', 'Wine glass'],
  ['las la-wine-glass-alt', 'Wine glass alt'],
  ['las la-archway', 'Archway'],
  ['las la-building', 'Building'],
  ['las la-church', 'Church'],
  ['las la-city', 'City'],
  ['las la-clinic-medical', 'Clinic medical'],
  ['las la-dungeon', 'Dungeon'],
  ['las la-gopuram', 'Gopuram'],
  ['las la-home', 'Home'],
  ['las la-hospital', 'Hospital'],
  ['las la-hospital-alt', 'Hospital alt'],
  ['las la-hotel', 'Hotel'],
  ['las la-house-damage', 'House damage'],
  ['las la-igloo', 'Igloo'],
  ['las la-industry', 'Industry'],
  ['las la-kaaba', 'Kaaba'],
  ['las la-landmark', 'Landmark'],
  ['las la-monument', 'Monument'],
  ['las la-mosque', 'Mosque'],
  ['las la-place-of-worship', 'Place of worship'],
  ['las la-school', 'School'],
  ['las la-store', 'Store'],
  ['las la-store-alt', 'Store alt'],
  ['las la-synagogue', 'Synagogue'],
  ['las la-torii-gate', 'Torii gate'],
  ['las la-university', 'University'],
  ['las la-vihara', 'Vihara'],
  ['las la-warehouse', 'Warehouse'],
  ['las la-address-book', 'Address book'],
  ['las la-address-card', 'Address card'],
  ['las la-archive', 'Archive'],
  ['las la-balance-scale', 'Balance scale'],
  ['las la-balance-scale-left', 'Balance scale left'],
  ['las la-balance-scale-right', 'Balance scale right'],
  ['las la-birthday-cake', 'Birthday cake'],
  ['las la-book', 'Book'],
  ['las la-briefcase', 'Briefcase'],
  ['las la-bullhorn', 'Bullhorn'],
  ['las la-bullseye', 'Bullseye'],
  ['las la-business-time', 'Business time'],
  ['las la-calculator', 'Calculator'],
  ['las la-calendar', 'Calendar'],
  ['las la-calendar-alt', 'Calendar alt'],
  ['las la-certificate', 'Certificate'],
  ['las la-chart-area', 'Chart area'],
  ['las la-chart-bar', 'Chart bar'],
  ['las la-chart-pie', 'Chart pie'],
  ['las la-clipboard', 'Clipboard'],
  ['las la-columns', 'Columns'],
  ['las la-compass', 'Compass'],
  ['las la-copy', 'Copy'],
  ['las la-copyright', 'Copyright'],
  ['las la-cut', 'Cut'],
  ['las la-edit', 'Edit'],
  ['las la-envelope', 'Envelope'],
  ['las la-envelope-open', 'Envelope open'],
  ['las la-envelope-square', 'Envelope square'],
  ['las la-eraser', 'Eraser'],
  ['las la-fax', 'Fax'],
  ['las la-file', 'File'],
  ['las la-file-alt', 'File alt'],
  ['las la-folder', 'Folder'],
  ['las la-folder-minus', 'Folder minus'],
  ['las la-folder-open', 'Folder open'],
  ['las la-folder-plus', 'Folder plus'],
  ['las la-glasses', 'Glasses'],
  ['las la-globe', 'Globe'],
  ['las la-highlighter', 'Highlighter'],
  ['las la-marker', 'Marker'],
  ['las la-paperclip', 'Paperclip'],
  ['las la-paste', 'Paste'],
  ['las la-pen', 'Pen'],
  ['las la-pen-alt', 'Pen alt'],
  ['las la-pen-fancy', 'Pen fancy'],
  ['las la-pen-nib', 'Pen nib'],
  ['las la-pen-square', 'Pen square'],
  ['las la-pencil-alt', 'Pencil alt'],
  ['las la-percent', 'Percent'],
  ['las la-phone', 'Phone'],
  ['las la-phone-alt', 'Phone alt'],
  ['las la-phone-slash', 'Phone slash'],
  ['las la-phone-square', 'Phone square'],
  ['las la-phone-square-alt', 'Phone square alt'],
  ['las la-print', 'Print'],
  ['las la-project-diagram', 'Project diagram'],
  ['las la-registered', 'Registered'],
  ['las la-save', 'Save'],
  ['las la-sitemap', 'Sitemap'],
  ['las la-socks', 'Socks'],
  ['las la-sticky-note', 'Sticky note'],
  ['las la-stream', 'Stream'],
  ['las la-table', 'Table'],
  ['las la-tag', 'Tag'],
  ['las la-tags', 'Tags'],
  ['las la-tasks', 'Tasks'],
  ['las la-thumbtack', 'Thumbtack'],
  ['las la-trademark', 'Trademark'],
  ['las la-wallet', 'Wallet'],
  ['las la-binoculars', 'Binoculars'],
  ['las la-fire', 'Fire'],
  ['las la-fire-alt', 'Fire alt'],
  ['las la-first-aid', 'First aid'],
  ['las la-map', 'Map'],
  ['las la-map-marked', 'Map marked'],
  ['las la-map-marked-alt', 'Map marked alt'],
  ['las la-map-signs', 'Map signs'],
  ['las la-route', 'Route'],
  ['las la-toilet-paper', 'Toilet paper'],
  ['las la-dollar-sign', 'Dollar sign'],
  ['las la-donate', 'Donate'],
  ['las la-gift', 'Gift'],
  ['las la-hand-holding-heart', 'Hand holding heart'],
  ['las la-hand-holding-usd', 'Hand holding usd'],
  ['las la-hands-helping', 'Hands helping'],
  ['las la-handshake', 'Handshake'],
  ['las la-heart', 'Heart'],
  ['las la-leaf', 'Leaf'],
  ['las la-parachute-box', 'Parachute box'],
  ['las la-piggy-bank', 'Piggy bank'],
  ['las la-ribbon', 'Ribbon'],
  ['las la-seedling', 'Seedling'],
  ['las la-comment', 'Comment'],
  ['las la-comment-alt', 'Comment alt'],
  ['las la-comment-dots', 'Comment dots'],
  ['las la-comment-medical', 'Comment medical'],
  ['las la-comment-slash', 'Comment slash'],
  ['las la-comments', 'Comments'],
  ['las la-frown', 'Frown'],
  ['las la-icons', 'Icons'],
  ['las la-meh', 'Meh'],
  ['las la-poo', 'Poo'],
  ['las la-quote-left', 'Quote left'],
  ['las la-quote-right', 'Quote right'],
  ['las la-smile', 'Smile'],
  ['las la-sms', 'Sms'],
  ['las la-video-slash', 'Video slash'],
  ['las la-chess', 'Chess'],
  ['las la-chess-bishop', 'Chess bishop'],
  ['las la-chess-board', 'Chess board'],
  ['las la-chess-king', 'Chess king'],
  ['las la-chess-knight', 'Chess knight'],
  ['las la-chess-pawn', 'Chess pawn'],
  ['las la-chess-queen', 'Chess queen'],
  ['las la-chess-rook', 'Chess rook'],
  ['las la-square-full', 'Square full'],
  ['las la-baby', 'Baby'],
  ['las la-baby-carriage', 'Baby carriage'],
  ['las la-bath', 'Bath'],
  ['las la-biking', 'Biking'],
  ['las la-cookie', 'Cookie'],
  ['las la-cookie-bite', 'Cookie bite'],
  ['las la-gamepad', 'Gamepad'],
  ['las la-ice-cream', 'Ice cream'],
  ['las la-mitten', 'Mitten'],
  ['las la-robot', 'Robot'],
  ['las la-shapes', 'Shapes'],
  ['las la-snowman', 'Snowman'],
  ['las la-graduation-cap', 'Graduation cap'],
  ['las la-hat-cowboy', 'Hat cowboy'],
  ['las la-hat-cowboy-side', 'Hat cowboy side'],
  ['las la-hat-wizard', 'Hat wizard'],
  ['las la-shoe-prints', 'Shoe prints'],
  ['las la-tshirt', 'Tshirt'],
  ['las la-user-tie', 'User tie'],
  ['las la-barcode', 'Barcode'],
  ['las la-bug', 'Bug'],
  ['las la-code', 'Code'],
  ['las la-code-branch', 'Code branch'],
  ['las la-file-code', 'File code'],
  ['las la-filter', 'Filter'],
  ['las la-fire-extinguisher', 'Fire extinguisher'],
  ['las la-keyboard', 'Keyboard'],
  ['las la-laptop-code', 'Laptop code'],
  ['las la-microchip', 'Microchip'],
  ['las la-qrcode', 'Qrcode'],
  ['las la-shield-alt', 'Shield alt'],
  ['las la-terminal', 'Terminal'],
  ['las la-user-secret', 'User secret'],
  ['las la-window-close', 'Window close'],
  ['las la-window-maximize', 'Window maximize'],
  ['las la-window-minimize', 'Window minimize'],
  ['las la-window-restore', 'Window restore'],
  ['las la-at', 'At'],
  ['las la-chalkboard', 'Chalkboard'],
  ['las la-inbox', 'Inbox'],
  ['las la-language', 'Language'],
  ['las la-mobile', 'Mobile'],
  ['las la-mobile-alt', 'Mobile alt'],
  ['las la-paper-plane', 'Paper plane'],
  ['las la-voicemail', 'Voicemail'],
  ['las la-wifi', 'Wifi'],
  ['las la-database', 'Database'],
  ['las la-desktop', 'Desktop'],
  ['las la-ethernet', 'Ethernet'],
  ['las la-hdd', 'Hdd'],
  ['las la-laptop', 'Laptop'],
  ['las la-memory', 'Memory'],
  ['las la-mouse', 'Mouse'],
  ['las la-plug', 'Plug'],
  ['las la-power-off', 'Power off'],
  ['las la-satellite', 'Satellite'],
  ['las la-satellite-dish', 'Satellite dish'],
  ['las la-sd-card', 'Sd card'],
  ['las la-server', 'Server'],
  ['las la-sim-card', 'Sim card'],
  ['las la-tablet', 'Tablet'],
  ['las la-tablet-alt', 'Tablet alt'],
  ['las la-brush', 'Brush'],
  ['las la-drafting-compass', 'Drafting compass'],
  ['las la-dumpster', 'Dumpster'],
  ['las la-hammer', 'Hammer'],
  ['las la-hard-hat', 'Hard hat'],
  ['las la-paint-roller', 'Paint roller'],
  ['las la-pencil-ruler', 'Pencil ruler'],
  ['las la-ruler', 'Ruler'],
  ['las la-ruler-combined', 'Ruler combined'],
  ['las la-ruler-horizontal', 'Ruler horizontal'],
  ['las la-ruler-vertical', 'Ruler vertical'],
  ['las la-screwdriver', 'Screwdriver'],
  ['las la-toolbox', 'Toolbox'],
  ['las la-tools', 'Tools'],
  ['las la-wrench', 'Wrench'],
  ['las la-euro-sign', 'Euro sign'],
  ['las la-hryvnia', 'Hryvnia'],
  ['las la-lira-sign', 'Lira sign'],
  ['las la-money-bill', 'Money bill'],
  ['las la-money-bill-alt', 'Money bill alt'],
  ['las la-money-bill-wave', 'Money bill wave'],
  ['las la-money-bill-wave-alt', 'Money bill wave alt'],
  ['las la-money-check', 'Money check'],
  ['las la-money-check-alt', 'Money check alt'],
  ['las la-pound-sign', 'Pound sign'],
  ['las la-ruble-sign', 'Ruble sign'],
  ['las la-rupee-sign', 'Rupee sign'],
  ['las la-shekel-sign', 'Shekel sign'],
  ['las la-tenge', 'Tenge'],
  ['las la-won-sign', 'Won sign'],
  ['las la-yen-sign', 'Yen sign'],
  ['las la-calendar-check', 'Calendar check'],
  ['las la-calendar-minus', 'Calendar minus'],
  ['las la-calendar-plus', 'Calendar plus'],
  ['las la-calendar-times', 'Calendar times'],
  ['las la-clock', 'Clock'],
  ['las la-hourglass', 'Hourglass'],
  ['las la-hourglass-end', 'Hourglass end'],
  ['las la-hourglass-half', 'Hourglass half'],
  ['las la-hourglass-start', 'Hourglass start'],
  ['las la-stopwatch', 'Stopwatch'],
  ['las la-adjust', 'Adjust'],
  ['las la-bezier-curve', 'Bezier curve'],
  ['las la-clone', 'Clone'],
  ['las la-crop', 'Crop'],
  ['las la-crop-alt', 'Crop alt'],
  ['las la-crosshairs', 'Crosshairs'],
  ['las la-draw-polygon', 'Draw polygon'],
  ['las la-eye', 'Eye'],
  ['las la-eye-dropper', 'Eye dropper'],
  ['las la-eye-slash', 'Eye slash'],
  ['las la-fill', 'Fill'],
  ['las la-fill-drip', 'Fill drip'],
  ['las la-layer-group', 'Layer group'],
  ['las la-magic', 'Magic'],
  ['las la-object-group', 'Object group'],
  ['las la-object-ungroup', 'Object ungroup'],
  ['las la-paint-brush', 'Paint brush'],
  ['las la-palette', 'Palette'],
  ['las la-splotch', 'Splotch'],
  ['las la-spray-can', 'Spray can'],
  ['las la-stamp', 'Stamp'],
  ['las la-swatchbook', 'Swatchbook'],
  ['las la-tint', 'Tint'],
  ['las la-tint-slash', 'Tint slash'],
  ['las la-vector-square', 'Vector square'],
  ['las la-align-center', 'Align center'],
  ['las la-align-justify', 'Align justify'],
  ['las la-align-left', 'Align left'],
  ['las la-align-right', 'Align right'],
  ['las la-bold', 'Bold'],
  ['las la-border-all', 'Border all'],
  ['las la-border-none', 'Border none'],
  ['las la-border-style', 'Border style'],
  ['las la-font', 'Font'],
  ['las la-heading', 'Heading'],
  ['las la-i-cursor', 'I cursor'],
  ['las la-indent', 'Indent'],
  ['las la-italic', 'Italic'],
  ['las la-link', 'Link'],
  ['las la-list', 'List'],
  ['las la-list-alt', 'List alt'],
  ['las la-list-ol', 'List ol'],
  ['las la-list-ul', 'List ul'],
  ['las la-outdent', 'Outdent'],
  ['las la-paragraph', 'Paragraph'],
  ['las la-remove-format', 'Remove format'],
  ['las la-spell-check', 'Spell check'],
  ['las la-strikethrough', 'Strikethrough'],
  ['las la-subscript', 'Subscript'],
  ['las la-superscript', 'Superscript'],
  ['las la-th', 'Th'],
  ['las la-th-large', 'Th large'],
  ['las la-th-list', 'Th list'],
  ['las la-trash', 'Trash'],
  ['las la-trash-alt', 'Trash alt'],
  ['las la-trash-restore', 'Trash restore'],
  ['las la-trash-restore-alt', 'Trash restore alt'],
  ['las la-underline', 'Underline'],
  ['las la-unlink', 'Unlink'],
  ['las la-atom', 'Atom'],
  ['las la-award', 'Award'],
  ['las la-book-open', 'Book open'],
  ['las la-book-reader', 'Book reader'],
  ['las la-chalkboard-teacher', 'Chalkboard teacher'],
  ['las la-microscope', 'Microscope'],
  ['las la-theater-masks', 'Theater masks'],
  ['las la-user-graduate', 'User graduate'],
  ['las la-angry', 'Angry'],
  ['las la-dizzy', 'Dizzy'],
  ['las la-flushed', 'Flushed'],
  ['las la-frown-open', 'Frown open'],
  ['las la-grimace', 'Grimace'],
  ['las la-grin', 'Grin'],
  ['las la-grin-alt', 'Grin alt'],
  ['las la-grin-beam', 'Grin beam'],
  ['las la-grin-beam-sweat', 'Grin beam sweat'],
  ['las la-grin-hearts', 'Grin hearts'],
  ['las la-grin-squint', 'Grin squint'],
  ['las la-grin-squint-tears', 'Grin squint tears'],
  ['las la-grin-stars', 'Grin stars'],
  ['las la-grin-tears', 'Grin tears'],
  ['las la-grin-tongue', 'Grin tongue'],
  ['las la-grin-tongue-squint', 'Grin tongue squint'],
  ['las la-grin-tongue-wink', 'Grin tongue wink'],
  ['las la-grin-wink', 'Grin wink'],
  ['las la-kiss', 'Kiss'],
  ['las la-kiss-beam', 'Kiss beam'],
  ['las la-kiss-wink-heart', 'Kiss wink heart'],
  ['las la-laugh', 'Laugh'],
  ['las la-laugh-beam', 'Laugh beam'],
  ['las la-laugh-squint', 'Laugh squint'],
  ['las la-laugh-wink', 'Laugh wink'],
  ['las la-meh-blank', 'Meh blank'],
  ['las la-meh-rolling-eyes', 'Meh rolling eyes'],
  ['las la-sad-cry', 'Sad cry'],
  ['las la-sad-tear', 'Sad tear'],
  ['las la-smile-beam', 'Smile beam'],
  ['las la-smile-wink', 'Smile wink'],
  ['las la-surprise', 'Surprise'],
  ['las la-tired', 'Tired'],
  ['las la-battery-empty', 'Battery empty'],
  ['las la-battery-full', 'Battery full'],
  ['las la-battery-half', 'Battery half'],
  ['las la-battery-quarter', 'Battery quarter'],
  ['las la-battery-three-quarters', 'Battery three quarters'],
  ['las la-burn', 'Burn'],
  ['las la-lightbulb', 'Lightbulb'],
  ['las la-poop', 'Poop'],
  ['las la-solar-panel', 'Solar panel'],
  ['las la-sun', 'Sun'],
  ['las la-water', 'Water'],
  ['las la-file-archive', 'File archive'],
  ['las la-file-excel', 'File excel'],
  ['las la-file-image', 'File image'],
  ['las la-file-pdf', 'File pdf'],
  ['las la-file-powerpoint', 'File powerpoint'],
  ['las la-file-word', 'File word'],
  ['las la-cash-register', 'Cash register'],
  ['las la-coins', 'Coins'],
  ['las la-comment-dollar', 'Comment dollar'],
  ['las la-comments-dollar', 'Comments dollar'],
  ['las la-credit-card', 'Credit card'],
  ['las la-file-invoice', 'File invoice'],
  ['las la-file-invoice-dollar', 'File invoice dollar'],
  ['las la-percentage', 'Percentage'],
  ['las la-receipt', 'Receipt'],
  ['las la-bicycle', 'Bicycle'],
  ['las la-heartbeat', 'Heartbeat'],
  ['las la-running', 'Running'],
  ['las la-skating', 'Skating'],
  ['las la-skiing', 'Skiing'],
  ['las la-skiing-nordic', 'Skiing nordic'],
  ['las la-snowboarding', 'Snowboarding'],
  ['las la-spa', 'Spa'],
  ['las la-swimmer', 'Swimmer'],
  ['las la-walking', 'Walking'],
  ['las la-bacon', 'Bacon'],
  ['las la-bone', 'Bone'],
  ['las la-bread-slice', 'Bread slice'],
  ['las la-candy-cane', 'Candy cane'],
  ['las la-carrot', 'Carrot'],
  ['las la-cheese', 'Cheese'],
  ['las la-cloud-meatball', 'Cloud meatball'],
  ['las la-egg', 'Egg'],
  ['las la-hamburger', 'Hamburger'],
  ['las la-hotdog', 'Hotdog'],
  ['las la-lemon', 'Lemon'],
  ['las la-pepper-hot', 'Pepper hot'],
  ['las la-pizza-slice', 'Pizza slice'],
  ['las la-stroopwafel', 'Stroopwafel'],
  ['las la-dice', 'Dice'],
  ['las la-dice-d20', 'Dice d20'],
  ['las la-dice-d6', 'Dice d6'],
  ['las la-dice-five', 'Dice five'],
  ['las la-dice-four', 'Dice four'],
  ['las la-dice-one', 'Dice one'],
  ['las la-dice-six', 'Dice six'],
  ['las la-dice-three', 'Dice three'],
  ['las la-dice-two', 'Dice two'],
  ['las la-ghost', 'Ghost'],
  ['las la-headset', 'Headset'],
  ['las la-puzzle-piece', 'Puzzle piece'],
  ['las la-genderless', 'Genderless'],
  ['las la-mars', 'Mars'],
  ['las la-mars-double', 'Mars double'],
  ['las la-mars-stroke', 'Mars stroke'],
  ['las la-mars-stroke-h', 'Mars stroke h'],
  ['las la-mars-stroke-v', 'Mars stroke v'],
  ['las la-mercury', 'Mercury'],
  ['las la-neuter', 'Neuter'],
  ['las la-transgender', 'Transgender'],
  ['las la-transgender-alt', 'Transgender alt'],
  ['las la-venus', 'Venus'],
  ['las la-venus-double', 'Venus double'],
  ['las la-venus-mars', 'Venus mars'],
  ['las la-book-dead', 'Book dead'],
  ['las la-broom', 'Broom'],
  ['las la-cloud-moon', 'Cloud moon'],
  ['las la-mask', 'Mask'],
  ['las la-allergies', 'Allergies'],
  ['las la-fist-raised', 'Fist raised'],
  ['las la-hand-holding', 'Hand holding'],
  ['las la-hand-lizard', 'Hand lizard'],
  ['las la-hand-middle-finger', 'Hand middle finger'],
  ['las la-hand-paper', 'Hand paper'],
  ['las la-hand-peace', 'Hand peace'],
  ['las la-hand-rock', 'Hand rock'],
  ['las la-hand-scissors', 'Hand scissors'],
  ['las la-hand-spock', 'Hand spock'],
  ['las la-hands', 'Hands'],
  ['las la-praying-hands', 'Praying hands'],
  ['las la-thumbs-down', 'Thumbs down'],
  ['las la-thumbs-up', 'Thumbs up'],
  ['las la-h-square', 'H square'],
  ['las la-medkit', 'Medkit'],
  ['las la-plus-square', 'Plus square'],
  ['las la-prescription', 'Prescription'],
  ['las la-stethoscope', 'Stethoscope'],
  ['las la-user-md', 'User md'],
  ['las la-gifts', 'Gifts'],
  ['las la-holly-berry', 'Holly berry'],
  ['las la-sleigh', 'Sleigh'],
  ['las la-bed', 'Bed'],
  ['las la-concierge-bell', 'Concierge bell'],
  ['las la-door-closed', 'Door closed'],
  ['las la-door-open', 'Door open'],
  ['las la-dumbbell', 'Dumbbell'],
  ['las la-hot-tub', 'Hot tub'],
  ['las la-infinity', 'Infinity'],
  ['las la-key', 'Key'],
  ['las la-luggage-cart', 'Luggage cart'],
  ['las la-shower', 'Shower'],
  ['las la-smoking', 'Smoking'],
  ['las la-smoking-ban', 'Smoking ban'],
  ['las la-snowflake', 'Snowflake'],
  ['las la-suitcase', 'Suitcase'],
  ['las la-suitcase-rolling', 'Suitcase rolling'],
  ['las la-swimming-pool', 'Swimming pool'],
  ['las la-umbrella-beach', 'Umbrella beach'],
  ['las la-utensils', 'Utensils'],
  ['las la-chair', 'Chair'],
  ['las la-couch', 'Couch'],
  ['las la-fan', 'Fan'],
  ['las la-bolt', 'Bolt'],
  ['las la-camera', 'Camera'],
  ['las la-camera-retro', 'Camera retro'],
  ['las la-id-badge', 'Id badge'],
  ['las la-id-card', 'Id card'],
  ['las la-image', 'Image'],
  ['las la-images', 'Images'],
  ['las la-portrait', 'Portrait'],
  ['las la-sliders-h', 'Sliders h'],
  ['las la-ban', 'Ban'],
  ['las la-bars', 'Bars'],
  ['las la-blog', 'Blog'],
  ['las la-check', 'Check'],
  ['las la-check-circle', 'Check circle'],
  ['las la-check-double', 'Check double'],
  ['las la-check-square', 'Check square'],
  ['las la-cloud', 'Cloud'],
  ['las la-cog', 'Cog'],
  ['las la-cogs', 'Cogs'],
  ['las la-dot-circle', 'Dot circle'],
  ['las la-ellipsis-h', 'Ellipsis h'],
  ['las la-ellipsis-v', 'Ellipsis v'],
  ['las la-file-download', 'File download'],
  ['las la-file-export', 'File export'],
  ['las la-file-import', 'File import'],
  ['las la-file-upload', 'File upload'],
  ['las la-fingerprint', 'Fingerprint'],
  ['las la-flag', 'Flag'],
  ['las la-flag-checkered', 'Flag checkered'],
  ['las la-grip-horizontal', 'Grip horizontal'],
  ['las la-grip-lines', 'Grip lines'],
  ['las la-grip-lines-vertical', 'Grip lines vertical'],
  ['las la-grip-vertical', 'Grip vertical'],
  ['las la-hashtag', 'Hashtag'],
  ['las la-info', 'Info'],
  ['las la-info-circle', 'Info circle'],
  ['las la-medal', 'Medal'],
  ['las la-minus', 'Minus'],
  ['las la-minus-circle', 'Minus circle'],
  ['las la-minus-square', 'Minus square'],
  ['las la-plus', 'Plus'],
  ['las la-plus-circle', 'Plus circle'],
  ['las la-question', 'Question'],
  ['las la-search', 'Search'],
  ['las la-search-minus', 'Search minus'],
  ['las la-search-plus', 'Search plus'],
  ['las la-share-alt', 'Share alt'],
  ['las la-share-alt-square', 'Share alt square'],
  ['las la-signal', 'Signal'],
  ['las la-star', 'Star'],
  ['las la-star-half', 'Star half'],
  ['las la-times', 'Times'],
  ['las la-times-circle', 'Times circle'],
  ['las la-toggle-off', 'Toggle off'],
  ['las la-toggle-on', 'Toggle on'],
  ['las la-trophy', 'Trophy'],
  ['las la-user', 'User'],
  ['las la-user-alt', 'User alt'],
  ['las la-user-circle', 'User circle'],
  ['las la-box', 'Box'],
  ['las la-boxes', 'Boxes'],
  ['las la-clipboard-check', 'Clipboard check'],
  ['las la-clipboard-list', 'Clipboard list'],
  ['las la-dolly', 'Dolly'],
  ['las la-dolly-flatbed', 'Dolly flatbed'],
  ['las la-pallet', 'Pallet'],
  ['las la-shipping-fast', 'Shipping fast'],
  ['las la-anchor', 'Anchor'],
  ['las la-bomb', 'Bomb'],
  ['las la-bookmark', 'Bookmark'],
  ['las la-directions', 'Directions'],
  ['las la-fighter-jet', 'Fighter jet'],
  ['las la-gavel', 'Gavel'],
  ['las la-helicopter', 'Helicopter'],
  ['las la-life-ring', 'Life ring'],
  ['las la-magnet', 'Magnet'],
  ['las la-male', 'Male'],
  ['las la-map-marker', 'Map marker'],
  ['las la-map-marker-alt', 'Map marker alt'],
  ['las la-map-pin', 'Map pin'],
  ['las la-newspaper', 'Newspaper'],
  ['las la-parking', 'Parking'],
  ['las la-plane', 'Plane'],
  ['las la-restroom', 'Restroom'],
  ['las la-road', 'Road'],
  ['las la-rocket', 'Rocket'],
  ['las la-ship', 'Ship'],
  ['las la-shopping-bag', 'Shopping bag'],
  ['las la-shopping-basket', 'Shopping basket'],
  ['las la-shopping-cart', 'Shopping cart'],
  ['las la-snowplow', 'Snowplow'],
  ['las la-street-view', 'Street view'],
  ['las la-subway', 'Subway'],
  ['las la-ticket-alt', 'Ticket alt'],
  ['las la-traffic-light', 'Traffic light'],
  ['las la-train', 'Train'],
  ['las la-tram', 'Tram'],
  ['las la-umbrella', 'Umbrella'],
  ['las la-utensil-spoon', 'Utensil spoon'],
  ['las la-dharmachakra', 'Dharmachakra'],
  ['las la-ad', 'Ad'],
  ['las la-envelope-open-text', 'Envelope open text'],
  ['las la-funnel-dollar', 'Funnel dollar'],
  ['las la-mail-bulk', 'Mail bulk'],
  ['las la-poll', 'Poll'],
  ['las la-poll-h', 'Poll h'],
  ['las la-search-dollar', 'Search dollar'],
  ['las la-search-location', 'Search location'],
  ['las la-divide', 'Divide'],
  ['las la-equals', 'Equals'],
  ['las la-greater-than', 'Greater than'],
  ['las la-greater-than-equal', 'Greater than equal'],
  ['las la-less-than', 'Less than'],
  ['las la-less-than-equal', 'Less than equal'],
  ['las la-not-equal', 'Not equal'],
  ['las la-square-root-alt', 'Square root alt'],
  ['las la-wave-square', 'Wave square'],
  ['las la-band-aid', 'Band aid'],
  ['las la-biohazard', 'Biohazard'],
  ['las la-bong', 'Bong'],
  ['las la-book-medical', 'Book medical'],
  ['las la-brain', 'Brain'],
  ['las la-briefcase-medical', 'Briefcase medical'],
  ['las la-cannabis', 'Cannabis'],
  ['las la-capsules', 'Capsules'],
  ['las la-crutch', 'Crutch'],
  ['las la-diagnoses', 'Diagnoses'],
  ['las la-dna', 'Dna'],
  ['las la-file-medical', 'File medical'],
  ['las la-file-medical-alt', 'File medical alt'],
  ['las la-file-prescription', 'File prescription'],
  ['las la-hospital-symbol', 'Hospital symbol'],
  ['las la-id-card-alt', 'Id card alt'],
  ['las la-joint', 'Joint'],
  ['las la-laptop-medical', 'Laptop medical'],
  ['las la-mortar-pestle', 'Mortar pestle'],
  ['las la-notes-medical', 'Notes medical'],
  ['las la-pager', 'Pager'],
  ['las la-pills', 'Pills'],
  ['las la-prescription-bottle', 'Prescription bottle'],
  ['las la-prescription-bottle-alt', 'Prescription bottle alt'],
  ['las la-procedures', 'Procedures'],
  ['las la-star-of-life', 'Star of life'],
  ['las la-syringe', 'Syringe'],
  ['las la-tablets', 'Tablets'],
  ['las la-teeth', 'Teeth'],
  ['las la-teeth-open', 'Teeth open'],
  ['las la-thermometer', 'Thermometer'],
  ['las la-tooth', 'Tooth'],
  ['las la-user-nurse', 'User nurse'],
  ['las la-vial', 'Vial'],
  ['las la-vials', 'Vials'],
  ['las la-weight', 'Weight'],
  ['las la-x-ray', 'X ray'],
  ['las la-box-open', 'Box open'],
  ['las la-people-carry', 'People carry'],
  ['las la-sign', 'Sign'],
  ['las la-tape', 'Tape'],
  ['las la-truck-loading', 'Truck loading'],
  ['las la-truck-moving', 'Truck moving'],
  ['las la-drum', 'Drum'],
  ['las la-drum-steelpan', 'Drum steelpan'],
  ['las la-guitar', 'Guitar'],
  ['las la-headphones-alt', 'Headphones alt'],
  ['las la-record-vinyl', 'Record vinyl'],
  ['las la-cube', 'Cube'],
  ['las la-cubes', 'Cubes'],
  ['las la-digital-tachograph', 'Digital tachograph'],
  ['las la-futbol', 'Futbol'],
  ['las la-gem', 'Gem'],
  ['las la-heart-broken', 'Heart broken'],
  ['las la-lock', 'Lock'],
  ['las la-lock-open', 'Lock open'],
  ['las la-moon', 'Moon'],
  ['las la-ring', 'Ring'],
  ['las la-scroll', 'Scroll'],
  ['las la-space-shuttle', 'Space shuttle'],
  ['las la-toilet', 'Toilet'],
  ['las la-unlock', 'Unlock'],
  ['las la-unlock-alt', 'Unlock alt'],
  ['las la-backspace', 'Backspace'],
  ['las la-blender-phone', 'Blender phone'],
  ['las la-crown', 'Crown'],
  ['las la-dumpster-fire', 'Dumpster fire'],
  ['las la-file-csv', 'File csv'],
  ['las la-network-wired', 'Network wired'],
  ['las la-signature', 'Signature'],
  ['las la-skull', 'Skull'],
  ['las la-vr-cardboard', 'Vr cardboard'],
  ['las la-weight-hanging', 'Weight hanging'],
  ['las la-cart-plus', 'Cart plus'],
  ['las la-democrat', 'Democrat'],
  ['las la-flag-usa', 'Flag usa'],
  ['las la-person-booth', 'Person booth'],
  ['las la-republican', 'Republican'],
  ['las la-vote-yea', 'Vote yea'],
  ['las la-ankh', 'Ankh'],
  ['las la-bible', 'Bible'],
  ['las la-cross', 'Cross'],
  ['las la-hamsa', 'Hamsa'],
  ['las la-hanukiah', 'Hanukiah'],
  ['las la-haykal', 'Haykal'],
  ['las la-jedi', 'Jedi'],
  ['las la-journal-whills', 'Journal whills'],
  ['las la-khanda', 'Khanda'],
  ['las la-menorah', 'Menorah'],
  ['las la-om', 'Om'],
  ['las la-pastafarianism', 'Pastafarianism'],
  ['las la-peace', 'Peace'],
  ['las la-pray', 'Pray'],
  ['las la-quran', 'Quran'],
  ['las la-star-and-crescent', 'Star and crescent'],
  ['las la-star-of-david', 'Star of david'],
  ['las la-torah', 'Torah'],
  ['las la-yin-yang', 'Yin yang'],
  ['las la-temperature-high', 'Temperature high'],
  ['las la-temperature-low', 'Temperature low'],
  ['las la-meteor', 'Meteor'],
  ['las la-user-astronaut', 'User astronaut'],
  ['las la-file-contract', 'File contract'],
  ['las la-file-signature', 'File signature'],
  ['las la-passport', 'Passport'],
  ['las la-user-lock', 'User lock'],
  ['las la-user-shield', 'User shield'],
  ['las la-square', 'Square'],
  ['las la-user-friends', 'User friends'],
  ['las la-user-plus', 'User plus'],
  ['las la-users', 'Users'],
  ['las la-asterisk', 'Asterisk'],
  ['las la-circle-notch', 'Circle notch'],
  ['las la-compact-disc', 'Compact disc'],
  ['las la-slash', 'Slash'],
  ['las la-spinner', 'Spinner'],
  ['las la-baseball-ball', 'Baseball ball'],
  ['las la-basketball-ball', 'Basketball ball'],
  ['las la-bowling-ball', 'Bowling ball'],
  ['las la-golf-ball', 'Golf ball'],
  ['las la-hockey-puck', 'Hockey puck'],
  ['las la-quidditch', 'Quidditch'],
  ['las la-table-tennis', 'Table tennis'],
  ['las la-volleyball-ball', 'Volleyball ball'],
  ['las la-cloud-sun-rain', 'Cloud sun rain'],
  ['las la-rainbow', 'Rainbow'],
  ['las la-calendar-day', 'Calendar day'],
  ['las la-calendar-week', 'Calendar week'],
  ['las la-star-half-alt', 'Star half alt'],
  ['las la-thermometer-empty', 'Thermometer empty'],
  ['las la-thermometer-full', 'Thermometer full'],
  ['las la-thermometer-half', 'Thermometer half'],
  ['las la-thermometer-quarter', 'Thermometer quarter'],
  ['las la-thermometer-three-quarters', 'Thermometer three quarters'],
  ['las la-user-alt-slash', 'User alt slash'],
  ['las la-user-slash', 'User slash'],
  ['las la-atlas', 'Atlas'],
  ['las la-globe-africa', 'Globe africa'],
  ['las la-globe-americas', 'Globe americas'],
  ['las la-globe-asia', 'Globe asia'],
  ['las la-globe-europe', 'Globe europe'],
  ['las la-plane-arrival', 'Plane arrival'],
  ['las la-plane-departure', 'Plane departure'],
  ['las la-child', 'Child'],
  ['las la-female', 'Female'],
  ['las la-user-check', 'User check'],
  ['las la-user-clock', 'User clock'],
  ['las la-user-cog', 'User cog'],
  ['las la-user-edit', 'User edit'],
  ['las la-user-injured', 'User injured'],
  ['las la-user-minus', 'User minus'],
  ['las la-user-ninja', 'User ninja'],
  ['las la-user-tag', 'User tag'],
  ['las la-user-times', 'User times'],
  ['las la-users-cog', 'Users cog'],
  ['las la-cloud-moon-rain', 'Cloud moon rain'],
  ['las la-cloud-rain', 'Cloud rain'],
  ['las la-cloud-showers-heavy', 'Cloud showers heavy'],
  ['las la-poo-storm', 'Poo storm'],
  ['las la-smog', 'Smog'],
  ['las la-icicles', 'Icicles'],
  
  /* brands */
  
  ['lab la-accessible-icon', 'Accessible icon'],
  ['lab la-youtube', 'Youtube'],
  ['lab la-500px', '500px'],
  ['lab la-accusoft', 'Accusoft'],
  ['lab la-adn', 'Adn'],
  ['lab la-adobe', 'Adobe'],
  ['lab la-adversal', 'Adversal'],
  ['lab la-affiliatetheme', 'Affiliatetheme'],
  ['lab la-airbnb', 'Airbnb'],
  ['lab la-algolia', 'Algolia'],
  ['lab la-amazon', 'Amazon'],
  ['lab la-amilia', 'Amilia'],
  ['lab la-android', 'Android'],
  ['lab la-angellist', 'Angellist'],
  ['lab la-angrycreative', 'Angrycreative'],
  ['lab la-angular', 'Angular'],
  ['lab la-app-store', 'App store'],
  ['lab la-app-store-ios', 'App store ios'],
  ['lab la-apper', 'Apper'],
  ['lab la-apple', 'Apple'],
  ['lab la-artstation', 'Artstation'],
  ['lab la-asymmetrik', 'Asymmetrik'],
  ['lab la-atlassian', 'Atlassian'],
  ['lab la-audible', 'Audible'],
  ['lab la-autoprefixer', 'Autoprefixer'],
  ['lab la-avianex', 'Avianex'],
  ['lab la-aviato', 'Aviato'],
  ['lab la-aws', 'Aws'],
  ['lab la-bandcamp', 'Bandcamp'],
  ['lab la-battle-net', 'Battle net'],
  ['lab la-behance', 'Behance'],
  ['lab la-behance-square', 'Behance square'],
  ['lab la-bimobject', 'Bimobject'],
  ['lab la-bitbucket', 'Bitbucket'],
  ['lab la-bity', 'Bity'],
  ['lab la-black-tie', 'Black tie'],
  ['lab la-blackberry', 'Blackberry'],
  ['lab la-blogger', 'Blogger'],
  ['lab la-blogger-b', 'Blogger b'],
  ['lab la-bootstrap', 'Bootstrap'],
  ['lab la-buffer', 'Buffer'],
  ['lab la-buromobelexperte', 'Buromobelexperte'],
  ['lab la-buy-n-large', 'Buy n large'],
  ['lab la-buysellads', 'Buysellads'],
  ['lab la-canadian-maple-leaf', 'Canadian maple leaf'],
  ['lab la-centercode', 'Centercode'],
  ['lab la-centos', 'Centos'],
  ['lab la-chrome', 'Chrome'],
  ['lab la-chromecast', 'Chromecast'],
  ['lab la-cloudscale', 'Cloudscale'],
  ['lab la-cloudsmith', 'Cloudsmith'],
  ['lab la-cloudversify', 'Cloudversify'],
  ['lab la-codepen', 'Codepen'],
  ['lab la-codiepie', 'Codiepie'],
  ['lab la-confluence', 'Confluence'],
  ['lab la-connectdevelop', 'Connectdevelop'],
  ['lab la-contao', 'Contao'],
  ['lab la-cotton-bureau', 'Cotton bureau'],
  ['lab la-cpanel', 'Cpanel'],
  ['lab la-creative-commons', 'Creative commons'],
  ['lab la-creative-commons-by', 'Creative commons by'],
  ['lab la-creative-commons-nc', 'Creative commons nc'],
  ['lab la-creative-commons-nc-eu', 'Creative commons nc eu'],
  ['lab la-creative-commons-nc-jp', 'Creative commons nc jp'],
  ['lab la-creative-commons-nd', 'Creative commons nd'],
  ['lab la-creative-commons-pd', 'Creative commons pd'],
  ['lab la-creative-commons-pd-alt', 'Creative commons pd alt'],
  ['lab la-creative-commons-remix', 'Creative commons remix'],
  ['lab la-creative-commons-sa', 'Creative commons sa'],
  ['lab la-creative-commons-sampling', 'Creative commons sampling'],
  ['lab la-creative-commons-sampling-plus', 'Creative commons sampling plus'],
  ['lab la-creative-commons-share', 'Creative commons share'],
  ['lab la-creative-commons-zero', 'Creative commons zero'],
  ['lab la-css3', 'Css3'],
  ['lab la-css3-alt', 'Css3 alt'],
  ['lab la-cuttlefish', 'Cuttlefish'],
  ['lab la-dashcube', 'Dashcube'],
  ['lab la-delicious', 'Delicious'],
  ['lab la-deploydog', 'Deploydog'],
  ['lab la-deskpro', 'Deskpro'],
  ['lab la-dev', 'Dev'],
  ['lab la-deviantart', 'Deviantart'],
  ['lab la-dhl', 'Dhl'],
  ['lab la-diaspora', 'Diaspora'],
  ['lab la-digg', 'Digg'],
  ['lab la-digital-ocean', 'Digital ocean'],
  ['lab la-discord', 'Discord'],
  ['lab la-discourse', 'Discourse'],
  ['lab la-dochub', 'Dochub'],
  ['lab la-docker', 'Docker'],
  ['lab la-draft2digital', 'Draft2digital'],
  ['lab la-dribbble', 'Dribbble'],
  ['lab la-dribbble-square', 'Dribbble square'],
  ['lab la-dropbox', 'Dropbox'],
  ['lab la-drupal', 'Drupal'],
  ['lab la-dyalog', 'Dyalog'],
  ['lab la-earlybirds', 'Earlybirds'],
  ['lab la-ebay', 'Ebay'],
  ['lab la-edge', 'Edge'],
  ['lab la-elementor', 'Elementor'],
  ['lab la-ello', 'Ello'],
  ['lab la-ember', 'Ember'],
  ['lab la-empire', 'Empire'],
  ['lab la-envira', 'Envira'],
  ['lab la-erlang', 'Erlang'],
  ['lab la-etsy', 'Etsy'],
  ['lab la-evernote', 'Evernote'],
  ['lab la-expeditedssl', 'Expeditedssl'],
  ['lab la-facebook', 'Facebook'],
  ['lab la-facebook-f', 'Facebook f'],
  ['lab la-facebook-messenger', 'Facebook messenger'],
  ['lab la-facebook-square', 'Facebook square'],
  ['lab la-fedex', 'Fedex'],
  ['lab la-fedora', 'Fedora'],
  ['lab la-figma', 'Figma'],
  ['lab la-firefox', 'Firefox'],
  ['lab la-first-order', 'First order'],
  ['lab la-first-order-alt', 'First order alt'],
  ['lab la-firstdraft', 'Firstdraft'],
  ['lab la-flickr', 'Flickr'],
  ['lab la-flipboard', 'Flipboard'],
  ['lab la-fly', 'Fly'],
  ['lab la-font-awesome', 'Font awesome'],
  ['lab la-font-awesome-alt', 'Font awesome alt'],
  ['lab la-font-awesome-flag', 'Font awesome flag'],
  ['lab la-fonticons', 'Fonticons'],
  ['lab la-fonticons-fi', 'Fonticons fi'],
  ['lab la-fort-awesome', 'Fort awesome'],
  ['lab la-fort-awesome-alt', 'Fort awesome alt'],
  ['lab la-forumbee', 'Forumbee'],
  ['lab la-foursquare', 'Foursquare'],
  ['lab la-free-code-camp', 'Free code camp'],
  ['lab la-freebsd', 'Freebsd'],
  ['lab la-fulcrum', 'Fulcrum'],
  ['lab la-get-pocket', 'Get pocket'],
  ['lab la-git', 'Git'],
  ['lab la-git-alt', 'Git alt'],
  ['lab la-git-square', 'Git square'],
  ['lab la-github', 'Github'],
  ['lab la-github-alt', 'Github alt'],
  ['lab la-github-square', 'Github square'],
  ['lab la-gitkraken', 'Gitkraken'],
  ['lab la-gitlab', 'Gitlab'],
  ['lab la-gitter', 'Gitter'],
  ['lab la-glide', 'Glide'],
  ['lab la-glide-g', 'Glide g'],
  ['lab la-gofore', 'Gofore'],
  ['lab la-goodreads', 'Goodreads'],
  ['lab la-goodreads-g', 'Goodreads g'],
  ['lab la-google', 'Google'],
  ['lab la-google-drive', 'Google drive'],
  ['lab la-google-play', 'Google play'],
  ['lab la-google-plus', 'Google plus'],
  ['lab la-google-plus-g', 'Google plus g'],
  ['lab la-google-plus-square', 'Google plus square'],
  ['lab la-gratipay', 'Gratipay'],
  ['lab la-grav', 'Grav'],
  ['lab la-gripfire', 'Gripfire'],
  ['lab la-grunt', 'Grunt'],
  ['lab la-gulp', 'Gulp'],
  ['lab la-hacker-news', 'Hacker news'],
  ['lab la-hacker-news-square', 'Hacker news square'],
  ['lab la-hackerrank', 'Hackerrank'],
  ['lab la-hips', 'Hips'],
  ['lab la-hire-a-helper', 'Hire a helper'],
  ['lab la-hooli', 'Hooli'],
  ['lab la-hornbill', 'Hornbill'],
  ['lab la-hotjar', 'Hotjar'],
  ['lab la-houzz', 'Houzz'],
  ['lab la-html5', 'Html5'],
  ['lab la-hubspot', 'Hubspot'],
  ['lab la-imdb', 'Imdb'],
  ['lab la-instagram', 'Instagram'],
  ['lab la-intercom', 'Intercom'],
  ['lab la-internet-explorer', 'Internet explorer'],
  ['lab la-invision', 'Invision'],
  ['lab la-ioxhost', 'Ioxhost'],
  ['lab la-itch-io', 'Itch io'],
  ['lab la-itunes', 'Itunes'],
  ['lab la-itunes-note', 'Itunes note'],
  ['lab la-java', 'Java'],
  ['lab la-jenkins', 'Jenkins'],
  ['lab la-jira', 'Jira'],
  ['lab la-joget', 'Joget'],
  ['lab la-joomla', 'Joomla'],
  ['lab la-js', 'Js'],
  ['lab la-js-square', 'Js square'],
  ['lab la-jsfiddle', 'Jsfiddle'],
  ['lab la-kaggle', 'Kaggle'],
  ['lab la-keybase', 'Keybase'],
  ['lab la-keycdn', 'Keycdn'],
  ['lab la-kickstarter', 'Kickstarter'],
  ['lab la-kickstarter-k', 'Kickstarter k'],
  ['lab la-korvue', 'Korvue'],
  ['lab la-laravel', 'Laravel'],
  ['lab la-lastfm', 'Lastfm'],
  ['lab la-lastfm-square', 'Lastfm square'],
  ['lab la-leanpub', 'Leanpub'],
  ['lab la-less', 'Less'],
  ['lab la-line', 'Line'],
  ['lab la-linkedin', 'Linkedin'],
  ['lab la-linkedin-in', 'Linkedin in'],
  ['lab la-linode', 'Linode'],
  ['lab la-linux', 'Linux'],
  ['lab la-lyft', 'Lyft'],
  ['lab la-magento', 'Magento'],
  ['lab la-mailchimp', 'Mailchimp'],
  ['lab la-mandalorian', 'Mandalorian'],
  ['lab la-markdown', 'Markdown'],
  ['lab la-mastodon', 'Mastodon'],
  ['lab la-maxcdn', 'Maxcdn'],
  ['lab la-mdb', 'Mdb'],
  ['lab la-medapps', 'Medapps'],
  ['lab la-medium', 'Medium'],
  ['lab la-medium-m', 'Medium m'],
  ['lab la-medrt', 'Medrt'],
  ['lab la-meetup', 'Meetup'],
  ['lab la-megaport', 'Megaport'],
  ['lab la-mendeley', 'Mendeley'],
  ['lab la-microsoft', 'Microsoft'],
  ['lab la-mix', 'Mix'],
  ['lab la-mixcloud', 'Mixcloud'],
  ['lab la-mizuni', 'Mizuni'],
  ['lab la-modx', 'Modx'],
  ['lab la-monero', 'Monero'],
  ['lab la-neos', 'Neos'],
  ['lab la-nimblr', 'Nimblr'],
  ['lab la-node', 'Node'],
  ['lab la-node-js', 'Node js'],
  ['lab la-npm', 'Npm'],
  ['lab la-ns8', 'Ns8'],
  ['lab la-nutritionix', 'Nutritionix'],
  ['lab la-odnoklassniki', 'Odnoklassniki'],
  ['lab la-odnoklassniki-square', 'Odnoklassniki square'],
  ['lab la-opencart', 'Opencart'],
  ['lab la-openid', 'Openid'],
  ['lab la-opera', 'Opera'],
  ['lab la-optin-monster', 'Optin monster'],
  ['lab la-orcid', 'Orcid'],
  ['lab la-osi', 'Osi'],
  ['lab la-page4', 'Page4'],
  ['lab la-pagelines', 'Pagelines'],
  ['lab la-palfed', 'Palfed'],
  ['lab la-patreon', 'Patreon'],
  ['lab la-periscope', 'Periscope'],
  ['lab la-phabricator', 'Phabricator'],
  ['lab la-phoenix-framework', 'Phoenix framework'],
  ['lab la-phoenix-squadron', 'Phoenix squadron'],
  ['lab la-php', 'Php'],
  ['lab la-pied-piper', 'Pied piper'],
  ['lab la-pied-piper-alt', 'Pied piper alt'],
  ['lab la-pied-piper-hat', 'Pied piper hat'],
  ['lab la-pied-piper-pp', 'Pied piper pp'],
  ['lab la-pinterest', 'Pinterest'],
  ['lab la-pinterest-p', 'Pinterest p'],
  ['lab la-pinterest-square', 'Pinterest square'],
  ['lab la-product-hunt', 'Product hunt'],
  ['lab la-pushed', 'Pushed'],
  ['lab la-python', 'Python'],
  ['lab la-qq', 'Qq'],
  ['lab la-quinscape', 'Quinscape'],
  ['lab la-quora', 'Quora'],
  ['lab la-r-project', 'R project'],
  ['lab la-raspberry-pi', 'Raspberry pi'],
  ['lab la-ravelry', 'Ravelry'],
  ['lab la-react', 'React'],
  ['lab la-reacteurope', 'Reacteurope'],
  ['lab la-readme', 'Readme'],
  ['lab la-rebel', 'Rebel'],
  ['lab la-red-river', 'Red river'],
  ['lab la-reddit', 'Reddit'],
  ['lab la-reddit-alien', 'Reddit alien'],
  ['lab la-reddit-square', 'Reddit square'],
  ['lab la-redhat', 'Redhat'],
  ['lab la-renren', 'Renren'],
  ['lab la-replyd', 'Replyd'],
  ['lab la-researchgate', 'Researchgate'],
  ['lab la-resolving', 'Resolving'],
  ['lab la-rev', 'Rev'],
  ['lab la-rocketchat', 'Rocketchat'],
  ['lab la-rockrms', 'Rockrms'],
  ['lab la-safari', 'Safari'],
  ['lab la-salesforce', 'Salesforce'],
  ['lab la-sass', 'Sass'],
  ['lab la-schlix', 'Schlix'],
  ['lab la-scribd', 'Scribd'],
  ['lab la-searchengin', 'Searchengin'],
  ['lab la-sellcast', 'Sellcast'],
  ['lab la-sellsy', 'Sellsy'],
  ['lab la-servicestack', 'Servicestack'],
  ['lab la-shirtsinbulk', 'Shirtsinbulk'],
  ['lab la-shopware', 'Shopware'],
  ['lab la-simplybuilt', 'Simplybuilt'],
  ['lab la-sistrix', 'Sistrix'],
  ['lab la-sith', 'Sith'],
  ['lab la-sketch', 'Sketch'],
  ['lab la-skyatlas', 'Skyatlas'],
  ['lab la-skype', 'Skype'],
  ['lab la-slack', 'Slack'],
  ['lab la-slack-hash', 'Slack hash'],
  ['lab la-slideshare', 'Slideshare'],
  ['lab la-snapchat', 'Snapchat'],
  ['lab la-snapchat-ghost', 'Snapchat ghost'],
  ['lab la-snapchat-square', 'Snapchat square'],
  ['lab la-sourcetree', 'Sourcetree'],
  ['lab la-speakap', 'Speakap'],
  ['lab la-speaker-deck', 'Speaker deck'],
  ['lab la-squarespace', 'Squarespace'],
  ['lab la-stack-exchange', 'Stack exchange'],
  ['lab la-stack-overflow', 'Stack overflow'],
  ['lab la-stackpath', 'Stackpath'],
  ['lab la-staylinked', 'Staylinked'],
  ['lab la-sticker-mule', 'Sticker mule'],
  ['lab la-strava', 'Strava'],
  ['lab la-studiovinari', 'Studiovinari'],
  ['lab la-stumbleupon', 'Stumbleupon'],
  ['lab la-stumbleupon-circle', 'Stumbleupon circle'],
  ['lab la-superpowers', 'Superpowers'],
  ['lab la-supple', 'Supple'],
  ['lab la-suse', 'Suse'],
  ['lab la-swift', 'Swift'],
  ['lab la-symfony', 'Symfony'],
  ['lab la-teamspeak', 'Teamspeak'],
  ['lab la-telegram', 'Telegram'],
  ['lab la-telegram-plane', 'Telegram plane'],
  ['lab la-tencent-weibo', 'Tencent weibo'],
  ['lab la-the-red-yeti', 'The red yeti'],
  ['lab la-themeco', 'Themeco'],
  ['lab la-themeisle', 'Themeisle'],
  ['lab la-think-peaks', 'Think peaks'],
  ['lab la-trade-federation', 'Trade federation'],
  ['lab la-trello', 'Trello'],
  ['lab la-tripadvisor', 'Tripadvisor'],
  ['lab la-tumblr', 'Tumblr'],
  ['lab la-tumblr-square', 'Tumblr square'],
  ['lab la-twitter', 'Twitter'],
  ['lab la-twitter-square', 'Twitter square'],
  ['lab la-typo3', 'Typo3'],
  ['lab la-uber', 'Uber'],
  ['lab la-ubuntu', 'Ubuntu'],
  ['lab la-uikit', 'Uikit'],
  ['lab la-umbraco', 'Umbraco'],
  ['lab la-uniregistry', 'Uniregistry'],
  ['lab la-untappd', 'Untappd'],
  ['lab la-ups', 'Ups'],
  ['lab la-usb', 'Usb'],
  ['lab la-usps', 'Usps'],
  ['lab la-ussunnah', 'Ussunnah'],
  ['lab la-vaadin', 'Vaadin'],
  ['lab la-viacoin', 'Viacoin'],
  ['lab la-viadeo', 'Viadeo'],
  ['lab la-viadeo-square', 'Viadeo square'],
  ['lab la-viber', 'Viber'],
  ['lab la-vimeo', 'Vimeo'],
  ['lab la-vimeo-square', 'Vimeo square'],
  ['lab la-vimeo-v', 'Vimeo v'],
  ['lab la-vine', 'Vine'],
  ['lab la-vk', 'Vk'],
  ['lab la-vnv', 'Vnv'],
  ['lab la-vuejs', 'Vuejs'],
  ['lab la-waze', 'Waze'],
  ['lab la-weebly', 'Weebly'],
  ['lab la-weibo', 'Weibo'],
  ['lab la-weixin', 'Weixin'],
  ['lab la-whatsapp', 'Whatsapp'],
  ['lab la-whatsapp-square', 'Whatsapp square'],
  ['lab la-whmcs', 'Whmcs'],
  ['lab la-wikipedia-w', 'Wikipedia w'],
  ['lab la-windows', 'Windows'],
  ['lab la-wix', 'Wix'],
  ['lab la-wolf-pack-battalion', 'Wolf pack battalion'],
  ['lab la-wordpress', 'Wordpress'],
  ['lab la-wordpress-simple', 'Wordpress simple'],
  ['lab la-wpbeginner', 'Wpbeginner'],
  ['lab la-wpexplorer', 'Wpexplorer'],
  ['lab la-wpforms', 'Wpforms'],
  ['lab la-wpressr', 'Wpressr'],
  ['lab la-xing', 'Xing'],
  ['lab la-xing-square', 'Xing square'],
  ['lab la-y-combinator', 'Y combinator'],
  ['lab la-yahoo', 'Yahoo'],
  ['lab la-yammer', 'Yammer'],
  ['lab la-yandex', 'Yandex'],
  ['lab la-yandex-international', 'Yandex international'],
  ['lab la-yarn', 'Yarn'],
  ['lab la-yelp', 'Yelp'],
  ['lab la-yoast', 'Yoast'],
  ['lab la-youtube-square', 'Youtube square'],
  ['lab la-zhihu', 'Zhihu'],
  ['lab la-bluetooth', 'Bluetooth'],
  ['lab la-bluetooth-b', 'Bluetooth b'],
  ['lab la-bitcoin', 'Bitcoin'],
  ['lab la-btc', 'Btc'],
  ['lab la-ethereum', 'Ethereum'],
  ['lab la-gg', 'Gg'],
  ['lab la-gg-circle', 'Gg circle'],
  ['lab la-playstation', 'Playstation'],
  ['lab la-steam', 'Steam'],
  ['lab la-steam-square', 'Steam square'],
  ['lab la-steam-symbol', 'Steam symbol'],
  ['lab la-twitch', 'Twitch'],
  ['lab la-xbox', 'Xbox'],
  ['lab la-napster', 'Napster'],
  ['lab la-soundcloud', 'Soundcloud'],
  ['lab la-spotify', 'Spotify'],
  ['lab la-alipay', 'Alipay'],
  ['lab la-amazon-pay', 'Amazon pay'],
  ['lab la-apple-pay', 'Apple pay'],
  ['lab la-cc-amazon-pay', 'Cc amazon pay'],
  ['lab la-cc-amex', 'Cc amex'],
  ['lab la-cc-apple-pay', 'Cc apple pay'],
  ['lab la-cc-diners-club', 'Cc diners club'],
  ['lab la-cc-discover', 'Cc discover'],
  ['lab la-cc-jcb', 'Cc jcb'],
  ['lab la-cc-mastercard', 'Cc mastercard'],
  ['lab la-cc-paypal', 'Cc paypal'],
  ['lab la-cc-stripe', 'Cc stripe'],
  ['lab la-cc-visa', 'Cc visa'],
  ['lab la-google-wallet', 'Google wallet'],
  ['lab la-paypal', 'Paypal'],
  ['lab la-stripe', 'Stripe'],
  ['lab la-stripe-s', 'Stripe s'],
  ['lab la-galactic-republic', 'Galactic republic'],
  ['lab la-galactic-senate', 'Galactic senate'],
  ['lab la-jedi-order', 'Jedi order'],
  ['lab la-old-republic', 'Old republic'],
  ['lab la-acquisitions-incorporated', 'Acquisitions incorporated'],
  ['lab la-critical-role', 'Critical role'],
  ['lab la-d-and-d', 'D and d'],
  ['lab la-d-and-d-beyond', 'D and d beyond'],
  ['lab la-fantasy-flight-games', 'Fantasy flight games'],
  ['lab la-penny-arcade', 'Penny arcade'],
  ['lab la-wizards-of-the-coast', 'Wizards of the coast']
];

// icons.sort();
var lineawesomeIcons = '';
for (var i = 0; i < icons.length; i++) {
  var newTitle = '';
  var ctr = 0;
  var title = icons[i][1];
  title = title.split(' ');
  for (var x = 0; x < title.length; x++) {
    ctr++;
    newTitle += ctr == 3 ? '<br />' : '';
    newTitle += title[x] + ' ';
    ctr = ctr == 3 ? 0 : ctr;
  }
  lineawesomeIcons += '<a href="#" '
    + 'onclick="klik(this);return false;" title="' + icons[i][0] + '">'
    + '<span class="' + icons[i][0] + '"></span>'
    + '<div>' + newTitle + '</div>'
    + '</a>';
};

function klik(el) {
  document.getElementsByClassName('lineawesomeClass')[0]
    .getElementsByTagName('input')[0]
      .value = el.getAttribute('title');
  a = document.getElementById('lineawesome');
  a = a.getElementsByTagName('a');
  for (i = 0; i < a.length; i++) {
    a[i].className = '';
  }
  el.className += 'active';
};

function searchIcon(val) {
  var aydi = document.getElementById('lineawesome');
  var klases = aydi.getElementsByTagName('a');
  for (var i = 0, len = klases.length, klas, klasNeym; i < len; i++) {
    klas = klases[i];
    klasNeym = klas.getAttribute('title');
    if (klasNeym && klasNeym.indexOf(val) >= 0) {
      klas.style.display = 'block';
    } else {
      klas.style.display = 'none';
    }
  }
};

function setSpanColor(color) {
  el = document.getElementById('lineawesome');
  el = el.getElementsByTagName('span');
  for (i = 0; i < el.length; i++) {
    el[i].setAttribute('style', 'color:' + color)
  }
};

function setCheckboxes() {
  klases = '';
  klases += document.getElementsByClassName('spinning')[0]
    .getElementsByTagName('input')[0].checked 
    ? ' la-spin' : klases;

  klases += document.getElementsByClassName('fixedWidth')[0]
    .getElementsByTagName('input')[0].checked 
    ? ' la-fw' : klases;

  klases += document.getElementsByClassName('bordered')[0]
    .getElementsByTagName('input')[0].checked 
    ? ' la-border' : klases;

  klases += ' ' + document.getElementsByClassName('flippedRotation')[0]
    .getElementsByTagName('select')[0].value;

  el = document.getElementById('lineawesome');
  el = el.getElementsByTagName('span');
  for (i = 0; i < el.length; i++) {
    el[i].className = el[i].parentNode.getAttribute('title') + klases;
  }
};

function in_array(needle, haystack) {
  for (var i in haystack) {
    if (haystack[i] == needle) return true;
  }
  return false;
};
CKEDITOR.dialog.add('lineawesomeDialog', function(editor) {
  return {
    title: 'Insert LineAwesome Icon',
    minWidth: 600,
    minHeight: 400,
    resizable: false,
    contents: [{
      id: 'insertLineawesome',
      label: 'insertLineawesome',
      elements: [{
        type: 'hbox',
        widths: ['50%', '50%'],
        children: [{
          type: 'hbox',
          widths: ['75%', '25%'],
          children: [{
            type: 'text',
            id: 'colorChooser',
            className: 'colorChooser',
            label: 'Color',
            onKeyUp: function(e) {
              setSpanColor(e.sender.$.value);
            },
            setup: function(widget) {
              /* we don't want a default color but inherit it unless explicitly set */
              // color = widget.data.color != '' ? widget.data.color : '#000000';
              color = widget.data.color;
              this.setValue(color);
              setSpanColor(color);
            },
            commit: function(widget) {
              widget.setData('color', this.getValue());
            }
          }, {
            type: 'button',
            label: 'Select',
            style: 'margin-top:1.35em',
            onClick: function() {
              editor.getColorFromDialog(function(color) {
                document.getElementsByClassName('colorChooser')[0]
                  .getElementsByTagName('input')[0].value = color;
                setSpanColor(color);
              }, this);
            }
          }]
        }, {
          type: 'text',
          id: 'size',
          className: 'size',
          label: 'Size',
          setup: function(widget) {
            this.setValue(widget.data.size);
          },
          commit: function(widget) {
            widget.setData('size', this.getValue());
          }
        }]
      }, {
        type: 'hbox',
        widths: ['25%', '25%', '25%', '25%'],
        children: [{
          type: 'checkbox',
          id: 'spinning',
          className: 'spinning cke_dialog_ui_checkbox_input',
          label: 'Spinning',
          value: 'true',
          setup: function(widget) {
            var klases = widget.data.class;
            klases = klases.split(' ');
            document.getElementsByClassName('spinning')[0]
              .getElementsByTagName('input')[0].checked = in_array('la-spin', klases) 
              ? true : false;
            setCheckboxes();
          },
          onClick: function() {
            setCheckboxes();
          }
        }, {
          type: 'checkbox',
          id: 'fixedWidth',
          className: 'fixedWidth cke_dialog_ui_checkbox_input',
          label: 'Fixed Width',
          value: 'true',
          setup: function(widget) {
            var klases = widget.data.class;
            klases = klases.split(' ');
            document.getElementsByClassName('fixedWidth')[0]
              .getElementsByTagName('input')[0].checked = in_array('la-fw', klases)
              ? true : false;
            setCheckboxes();
          },
          onClick: function() {
            setCheckboxes();
          }
        }, {
          type: 'checkbox',
          id: 'bordered',
          className: 'bordered cke_dialog_ui_checkbox_input',
          label: 'Bordered',
          value: 'true',
          setup: function(widget) {
            var klases = widget.data.class;
            klases = klases.split(' ');
            document.getElementsByClassName('bordered')[0]
              .getElementsByTagName('input')[0].checked = in_array('la-border', klases) 
              ? true : false;
            setCheckboxes();
          },
          onClick: function() {
            setCheckboxes();
          }
        }, {
          type: 'select',
          id: 'flippedRotation',
          className: 'flippedRotation cke_dialog_ui_checkbox_input',
          label: 'Flipping and Rotating',
          items: [
            ['Normal', ''],
            ['Rotate 90', 'la-rotate-90'],
            ['Rotate 180', 'la-rotate-180'],
            ['Rotate 270', 'la-rotate-270'],
            ['Flip Horizontal', 'la-flip-horizontal'],
            ['Flip Vertical', 'la-flip-vertical']
            ['Flip Both', 'la-flip-both']
          ],
          setup: function(widget) {
            this.setValue(widget.data.flippedRotation ? widget.data.flippedRotation : '');
          },
          commit: function(widget) {
            widget.setData('flippedRotation', this.getValue());
          },
          onClick: function() {
            setCheckboxes();
          }
        }]
      }, {
        type: 'text',
        id: 'lineawesomeSearch',
        className: 'lineawesomeSearch cke_dialog_ui_input_text',
        label: 'Search',
        onKeyUp: function(e) {
          searchIcon(e.sender.$.value);
        }
      }, {
        type: 'text',
        id: 'lineawesomeClass',
        className: 'lineawesomeClass',
        style: 'display:none',
        setup: function(widget) {
          var klases = '';
          if (widget.data.class != '') {
            klases = widget.data.class;
            klases = klases.split(' ');
            in_array('la-border', klases) ? klases.splice(klases.indexOf('la-border'), 1) : '';
            in_array('la-fw', klases) ? klases.splice(klases.indexOf('la-fw'), 1) : '';
            in_array('la-spin', klases) ? klases.splice(klases.indexOf('la-spin'), 1) : '';
            in_array('la-rotate-90', klases) ? klases.splice(klases.indexOf('la-rotate-90'), 1) : '';
            in_array('la-rotate-180', klases) ? klases.splice(klases.indexOf('la-rotate-180'), 1) : '';
            in_array('la-rotate-270', klases) ? klases.splice(klases.indexOf('la-rotate-270'), 1) : '';
            in_array('la-flip-horizontal', klases) ? klases.splice(klases.indexOf('la-flip-horizontal'), 1) : '';
            in_array('la-flip-vertical', klases) ? klases.splice(klases.indexOf('la-flip-vertical'), 1) : '';
            in_array('la-flip-both', klases) ? klases.splice(klases.indexOf('la-flip-both'), 1) : '';
            klases = klases.join(' ');
          }
          this.setValue(klases);
        },
        commit: function(widget) {
          var klases = '';
          klases += document.getElementsByClassName('spinning')[0]
            .getElementsByTagName('input')[0].checked 
            ? ' la-spin' : klases;

          klases += document.getElementsByClassName('fixedWidth')[0]
            .getElementsByTagName('input')[0].checked 
            ? ' la-fw' : klases;

          klases += document.getElementsByClassName('bordered')[0]
            .getElementsByTagName('input')[0].checked 
            ? ' la-border' : klases;

          klases += ' ' + document.getElementsByClassName('flippedRotation')[0]
            .getElementsByTagName('select')[0].value;

          widget.setData('class', this.getValue() + klases);
        }
      }, {
        type: 'html',
        html: '<div id="lineawesome">' + lineawesomeIcons + '</div>'
      }]
    }],
    onOk: function() {
      glyphs = document.getElementById('lineawesome');
      glyphs = glyphs.getElementsByTagName('a');
      for (i = 0; i < glyphs.length; i++) {
        glyphs[i].firstChild.className = glyphs[i].getAttribute('title');
        glyphs[i].className = '';
        glyphs[i].style.display = '';
        glyphs[i].getElementsByTagName('span')[0].style.color = '';
      }
    }
  }
});
